/* Admin planning overlay. All private reads/writes require the ganttPlanner callable. */
(() => {
 'use strict';
 const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
 const day=s=>/^\d{4}-\d{2}-\d{2}$/.test(s||'')&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s?Date.parse(s)/86400000:null;
 let state=null,busy=false,session=0;
 const allowed=()=>typeof hasPersistentLeaderSession==='function'&&hasPersistentLeaderSession();
 function message(s){if($('gt-status'))$('gt-status').textContent=s;}
 async function call(action,extra={}){
  if(!allowed()||!functionsInstance)throw Error('Admin sign-in and the Gantt service are required.');
  const uid=auth.currentUser.uid,epoch=session;
  const result=await functionsInstance.httpsCallable('ganttPlanner')({action,...extra});
  if(epoch!==session||auth.currentUser?.uid!==uid||!allowed())throw Error('Session changed.');
  return result.data;
 }
 async function run(fn){if(busy)return;busy=true;const epoch=session;try{await fn();}catch(e){if(epoch===session)message(e.code==='functions/not-found'?'Gantt service is awaiting Firebase deployment. No plan has been saved.':e.message);}finally{busy=false;}}
 function mount(){
  $('gantt').innerHTML=`<div class="gt-heading"><div><span class="gt-eyebrow">ADMIN WORKSPACE · PRIVATE</span><h2>Project timeline</h2><p>Official milestones and your internal work targets.</p></div><button id="gt-refresh" type="button">Refresh tasks</button></div><p id="gt-status" role="status"></p><div id="gt-content" hidden><div class="gt-toolbar"><label>Month<input id="gt-month" type="month" value="${today().slice(0,7)}"></label><label>PIC<select id="gt-pic"><option value="">All members</option></select></label><button id="gt-add" type="button">+ Official milestone</button><button id="gt-bulk" type="button">Set missing starts</button><button id="gt-preview" type="button">Preview PDF</button></div><div id="gt-editor"></div><div class="gt-legend"><span class="gt-key gt-key-progress">In progress</span><span class="gt-key gt-key-done">Done</span><span class="gt-key gt-key-overdue">Overdue · unfinished</span><span class="gt-key gt-key-pending">Not started / unconfirmed</span><span class="gt-key gt-key-risk">Schedule warning</span><span class="gt-key-official">◆ Official deadline</span><span>● Internal target</span><span>Orange line = Today · Bars = planned duration</span></div><div id="gt-chart" class="gt-scroll"></div><div id="gt-unscheduled"></div><div id="gt-export" hidden></div><p class="gt-footnote">Internal dates are private planning targets. Shared task deadlines stay unchanged. Blank starts use task creation dates (Malaysia time), not confirmed work commencement. Status is the recorded task status, not a prediction.</p></div>`;
  $('gt-refresh').onclick=()=>run(load);$('gt-add').onclick=()=>editMilestone();$('gt-month').onchange=draw;$('gt-pic').onchange=draw;$('gt-preview').onclick=preview;$('gt-bulk').onclick=editBulk;
 }
 async function load(){message('Loading current tasks and plan…');const next=await call('read');state=next;$('gt-content').hidden=false;const old=$('gt-pic').value,names=[...new Set(state.tasks.flatMap(t=>[t.mainPIC,...(t.assigned||[])]).filter(Boolean))].sort();$('gt-pic').innerHTML='<option value="">All members</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(names.includes(old))$('gt-pic').value=old;$('gt-editor').innerHTML='';draw();message('Loaded current tasks. Starts use task creation dates automatically; manual starts take priority.');}
 // Legacy task IDs were generated with Date.now(); use Malaysia calendar dates.
 function creationStart(t){
  const stamp=Number(t.id);
  if(!/^\d{13}$/.test(String(t.id))||!Number.isSafeInteger(stamp)||stamp<Date.UTC(2020,0,1)||stamp>Date.now())return '';
  return new Date(stamp+8*3600000).toISOString().slice(0,10);
 }
 function effectiveStart(t,s){return s.start||creationStart(t);}
 function bulkCandidates(){return state.tasks.filter(t=>{const s=state.plan.schedules.find(s=>s.taskId===String(t.id))||{};return !effectiveStart(t,s)&&day(s.target||t.deadline)!==null;});}
 function editBulk(){
  if(!state||!allowed())return;
  const candidates=bulkCandidates();
  if(!candidates.length){message('All dated tasks already have a manual or automatic start.');return;}
  editor('<h3>Set missing starts together</h3><p>Applies to all '+candidates.length+' dated tasks without a manual or automatic start, across all months and PICs. Existing starts stay unchanged. This is a planning date, not evidence of actual work.</p><label>Shared planned start<input type="date" name="start" required></label><p>'+candidates.map(t=>esc(t.name)).join(' · ')+'</p>');
  $('gt-form').onsubmit=e=>{e.preventDefault();const start=new FormData(e.target).get('start'),current=bulkCandidates();
   if(day(start)===null)return;
   const invalid=current.filter(t=>{const s=state.plan.schedules.find(s=>s.taskId===String(t.id))||{};return start>(s.target||t.deadline);});
   if(invalid.length){message('Choose a start on or before every target. Earlier targets: '+invalid.map(t=>t.name).join(', '));return;}
   const schedules=state.plan.schedules.filter(s=>state.tasks.some(t=>String(t.id)===s.taskId)).map(s=>({...s}));
   for(const t of current){const s=schedules.find(s=>s.taskId===String(t.id));if(s)s.start=start;else schedules.push({taskId:String(t.id),start,target:'',milestoneId:''});}
   run(()=>save({...state.plan,schedules}));
  };
 }
 function taskTone(t){return t.status==='Done'?'gt-done':t.issues.includes('Past target')?'gt-overdue':t.issues.length?'gt-risk':t.status==='In Progress'?'gt-progress':'gt-pending';}
 function entries(){if(!state)return[];const pic=$('gt-pic').value;return state.tasks.filter(t=>!pic||t.mainPIC===pic||(t.assigned||[]).includes(pic)).map(t=>{const s=state.plan.schedules.find(s=>s.taskId===String(t.id))||{},m=state.plan.milestones.find(m=>m.id===s.milestoneId);const end=s.target||t.deadline||'',start=effectiveStart(t,s),issues=[];if(day(start)!==null&&day(end)!==null&&start>end)issues.push('Check dates');if(t.status!=='Done'&&day(end)!==null&&end<today())issues.push('Past target');if(m&&end&&end>m.date)issues.push('After official date');else if(m?.target&&end&&end>m.target)issues.push('After milestone target');return {...t,start,end,milestone:m,issues,status:t.status||'Not confirmed',internal:!!s.target};});}
 function range(){const m=$('gt-month').value;if(!/^\d{4}-\d{2}$/.test(m))return null;const start=day(m+'-01');if(start===null)return null;const d=new Date(start*86400000);const end=Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)/86400000-1;return {start,end,count:end-start+1};}
 function visible(t,r){const e=day(t.end),s=day(t.start);return e!==null&&(s!==null&&s<=e?s<=r.end&&e>=r.start:e>=r.start&&e<=r.end);}
 function draw(){if(!state||!allowed())return;const r=range();$('gt-export').hidden=true;if(!r){$('gt-chart').textContent='Select a valid month.';return;}const list=entries(),marks=state.plan.milestones.filter(m=>[m.date,m.target].some(d=>day(d)>=r.start&&day(d)<=r.end));
 const ticks=Array.from({length:r.count},(_,i)=>`<span>${i+1}</span>`).join('');let html=`<div class="gt-table"><div class="gt-row gt-axis"><div>Deliverable / PIC</div><div class="gt-days" style="grid-template-columns:repeat(${r.count},1fr)">${ticks}</div></div>`;
 const x=d=>(day(d)-r.start+.5)/r.count*100;
 const lane=(content)=>`<div class="gt-lane">${day(today())>=r.start&&day(today())<=r.end?`<span class="gt-today" style="left:${x(today())}%" title="Today"></span>`:''}${content}</div>`;
 if(marks.length)html+='<div class="gt-group">Official milestones</div>';
 for(const m of marks){let marksHtml='';if(day(m.date)>=r.start&&day(m.date)<=r.end)marksHtml+=`<span class="gt-marker" style="left:${x(m.date)}%" title="Official: ${esc(m.date)}">◆</span>`;if(m.target&&day(m.target)>=r.start&&day(m.target)<=r.end)marksHtml+=`<span class="gt-marker gt-target" style="left:${x(m.target)}%" title="Internal target: ${esc(m.target)}">●</span>`;html+=`<div class="gt-row"><button class="gt-label" data-m="${esc(m.id)}">${esc(m.name)}<small>Official ${esc(m.date)}${m.target?' · Target '+esc(m.target):''}</small></button>${lane(marksHtml)}</div>`;}
 const groups=new Map();for(const t of list.filter(t=>visible(t,r))){const key=t.milestone?.name||t.chapter||'Unlinked tasks';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(t);}
 for(const [name,tasks]of groups){if(tasks.length>1)html+=`<div class="gt-group">${esc(name)}</div>`;for(const t of tasks){const s=day(t.start),e=day(t.end);let bar;if(s!==null&&s<=e){const left=(Math.max(s,r.start)-r.start)/r.count*100,width=(Math.min(e,r.end)-Math.max(s,r.start)+1)/r.count*100;bar=`<button class="gt-bar ${taskTone(t)}" style="left:${left}%;width:${width}%" data-t="${esc(t.id)}" title="${esc(t.start)} → ${esc(t.end)} · ${esc(t.status)}${t.issues.length?' · '+esc(t.issues.join(' / ')):''}" aria-label="${esc(t.name)}: ${esc(t.start)} to ${esc(t.end)}">${esc(t.status)}</button>`;}else bar=`<button class="gt-marker" style="left:${x(t.end)}%" data-t="${esc(t.id)}" aria-label="${esc(t.name)} deadline ${esc(t.end)}">◆</button>`;html+=`<div class="gt-row"><button class="gt-label" data-t="${esc(t.id)}">${esc(t.name)}<small><span class="gt-pic-badge">${esc(t.mainPIC||'Unassigned')}</span> · ${esc(t.status)}${t.issues.length?' · '+esc(t.issues.join(' / ')):''}</small></button>${lane(bar)}</div>`;}}
 if(!marks.length&&!groups.size)html+='<p class="gt-empty">No dated work in this month. Add a milestone or choose another month.</p>';
 $('gt-chart').innerHTML=html+'</div>';
 const missing=list.filter(t=>day(t.end)===null);$('gt-unscheduled').innerHTML=`<details><summary>All milestones (${state.plan.milestones.length})</summary><div class="gt-chips">${state.plan.milestones.map(m=>`<button data-m="${esc(m.id)}">${esc(m.name)} · ${esc(m.date)}</button>`).join('')||'<p>No milestones yet. Add confirmed dates from the course outline.</p>'}</div></details><details ${missing.length?'open':''}><summary>Tasks without dates (${missing.length})</summary><div class="gt-chips">${missing.map(t=>`<button data-t="${esc(t.id)}">${esc(t.name)}</button>`).join('')}</div></details>`;
 for(const container of [$('gt-chart'),$('gt-unscheduled')]){container.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>editTask(b.dataset.t));container.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>editMilestone(b.dataset.m));}
 }
 async function save(plan){if(!allowed())return;await call('save',{plan,revision:state.plan.revision});await load();message('Private plan saved. Shared task deadlines unchanged.');}
 function editor(html){$('gt-editor').innerHTML=`<form id="gt-form" class="gt-form">${html}<div class="gt-actions"><button type="submit">Save private plan</button><button id="gt-cancel" type="button">Cancel</button></div></form>`;$('gt-cancel').onclick=()=>{$('gt-editor').innerHTML='';};$('gt-editor').scrollIntoView({block:'nearest',behavior:'smooth'});}
 function editMilestone(id){if(!state||!allowed())return;const m=state.plan.milestones.find(m=>m.id===id)||{id:crypto.randomUUID(),name:'',date:'',target:'',source:''};editor(`<h3>${id?'Edit':'Add'} official milestone</h3><label>Name<input name="name" required maxlength="160" value="${esc(m.name)}" placeholder="Report submission"></label><label>Official date<input name="date" type="date" required value="${esc(m.date)}"></label><label>Internal completion target<input name="target" type="date" value="${esc(m.target)}"></label><label>Source / course outline revision<input name="source" maxlength="300" value="${esc(m.source)}" placeholder="Course outline · Rev 2 · Week 8 confirmed"></label><p>Use confirmed dates only. A teaching week alone is not a confirmed calendar date.</p>`);$('gt-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),updated={id:m.id,...Object.fromEntries(f)};if(updated.target&&updated.target>updated.date){message('Internal target must be on or before the official date.');return;}run(()=>save({...state.plan,milestones:[...state.plan.milestones.filter(x=>x.id!==m.id),updated]}));};}
 function editTask(id){if(!state||!allowed())return;const t=state.tasks.find(t=>String(t.id)===id);if(!t)return;const s=state.plan.schedules.find(s=>s.taskId===id)||{};editor(`<h3>${esc(t.name)}</h3><p>${esc(t.mainPIC||'Unassigned')} · Recorded status: ${esc(t.status||'Not confirmed')} · Shared deadline: ${esc(t.deadline||'Not set')}</p><label>Linked milestone<select name="milestoneId"><option value="">No milestone</option>${state.plan.milestones.map(m=>`<option value="${esc(m.id)}" ${s.milestoneId===m.id?'selected':''}>${esc(m.name)} · ${esc(m.date)}</option>`).join('')}</select></label><label>Planned start<input name="start" type="date" value="${esc(s.start||'')}"></label><label>Internal task target<input name="target" type="date" value="${esc(s.target||'')}"></label><p>Leave start blank to use the task creation date automatically (Malaysia time). If unavailable, a deadline marker is shown. Leave target blank to use the existing task deadline.</p>`);$('gt-form').onsubmit=e=>{e.preventDefault();const v={taskId:id,...Object.fromEntries(new FormData(e.target))},end=v.target||t.deadline;if(v.start&&(!end||v.start>end)){message('Start must be on or before the internal target or task deadline.');return;}run(()=>save({...state.plan,schedules:[...state.plan.schedules.filter(s=>s.taskId!==id&&state.tasks.some(t=>String(t.id)===s.taskId)),v]}));};}
 function preview(){if(!state||!allowed()||!range())return;const list=entries().filter(t=>visible(t,range()));$('gt-export').hidden=false;$('gt-export').innerHTML=`<h3>Progress snapshot · ${esc($('gt-month').value)}</h3><p>${list.length} dated tasks · PIC: ${esc($('gt-pic').value||'All members')} · Snapshot ${today()}</p><p>Includes the selected month's Gantt, official milestones, recorded status, schedule warnings and tasks without dates. Private start/target dates will be included in the PDF.</p><button id="gt-download" type="button">Download PDF</button>`;$('gt-download').onclick=exportPdf;}
 function exportPdf(){
  if(!allowed()||!state)return;const JsPDF=window.jspdf?.jsPDF;if(!JsPDF){message('PDF library unavailable. Check connection and reload.');return;}const r=range();if(!r)return;
  const doc=new JsPDF({orientation:'landscape',unit:'mm',format:'a4'}),month=$('gt-month').value,pic=$('gt-pic').value||'All members',list=entries(),rows=[];
  state.plan.milestones.forEach(m=>{if([m.date,m.target].some(d=>day(d)!==null&&day(d)>=r.start&&day(d)<=r.end))rows.push({name:m.name,detail:`Official: ${m.date}${m.target?' | Internal: '+m.target:''}`,source:m.source,official:m.date,target:m.target});});
  list.filter(t=>visible(t,r)).forEach(t=>rows.push({name:t.name,detail:`${t.mainPIC||'Unassigned'} | ${t.status} | ${t.internal?'Internal target':'Task deadline'}: ${t.end}`,source:[t.milestone?.name||t.chapter,...t.issues].filter(Boolean).join(' | '),start:t.start,end:t.end,status:t.status,tone:taskTone(t),risk:t.issues.length}));
  const x0=126,w=157,x=d=>x0+(day(d)-r.start+.5)/r.count*w;let y;
  const clean=s=>String(s||'').replace(/[^\x20-\x7E]/g,' ');
  function header(){doc.setTextColor(30,45,65);doc.setFontSize(16);doc.text('Design Project | Progress Snapshot',14,16);doc.setFontSize(9);doc.text(`${month} | PIC: ${clean(pic)} | Snapshot: ${today()}`,14,23);doc.text('Internal dates are planning targets. Status reflects recorded task data; no update is not "on track".',14,29);doc.setFontSize(8);[1,8,15,22,r.count].filter((v,i,a)=>a.indexOf(v)===i).forEach(d=>doc.text(String(d),x(`${month}-${String(d).padStart(2,'0')}`),38,{align:'center'}));y=44;}
  header();if(!rows.length){doc.text('No dated work in the selected month.',14,y);y+=12;}
  rows.forEach(row=>{const lines=doc.splitTextToSize(clean(row.name),103),details=doc.splitTextToSize(clean(row.detail),103),source=doc.splitTextToSize(clean(row.source),103),h=Math.max(22,(lines.length+details.length+source.length)*4+5);if(y+h>190){doc.addPage();header();}doc.setFontSize(9);doc.setTextColor(30,45,65);doc.text(lines,14,y+4);doc.setFontSize(8);doc.setTextColor(95,106,122);doc.text(details,14,y+4+lines.length*4);if(source.length&&row.source)doc.text(source,14,y+4+(lines.length+details.length)*4);doc.setDrawColor(225,230,235);doc.line(14,y+h,283,y+h);
   if(row.official){if(day(row.official)>=r.start&&day(row.official)<=r.end){const xx=x(row.official);doc.setFillColor(43,71,108);doc.triangle(xx,y+6,xx-2,y+10,xx+2,y+10,'F');}if(row.target&&day(row.target)>=r.start&&day(row.target)<=r.end){doc.setFillColor(183,112,50);doc.circle(x(row.target),y+8,1.5,'F');}}
   else if(day(row.start)!==null&&row.start<=row.end){const a=Math.max(day(row.start),r.start),b=Math.min(day(row.end),r.end);doc.setFillColor(...(row.tone==='gt-done'?[21,128,61]:row.tone==='gt-overdue'?[185,28,28]:row.tone==='gt-risk'?[180,83,9]:row.tone==='gt-progress'?[37,99,235]:[100,116,139]));doc.roundedRect(x0+(a-r.start)/r.count*w,y+5,(b-a+1)/r.count*w,6,1,1,'F');}else{doc.setFillColor(70,95,126);doc.circle(x(row.end),y+8,1.5,'F');}y+=h;
  });
  const missing=list.filter(t=>day(t.end)===null);if(missing.length){doc.addPage();header();doc.setFontSize(11);doc.text('Tasks without dates',14,y);y+=9;for(const t of missing){const lines=doc.splitTextToSize(clean(`${t.name} | ${t.mainPIC||'Unassigned'} | ${t.status}`),265);if(y+lines.length*4>190){doc.addPage();header();}doc.setFontSize(9);doc.text(lines,14,y);y+=lines.length*4+4;}}
  const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(100,110,125);doc.text('Triangle: official milestone | Circle: target / deadline | Bar: planned duration',14,202);doc.text(`${i} / ${pages}`,283,202,{align:'right'});}doc.save(`DP_Progress_${month}_${today()}.pdf`);message('Progress snapshot exported.');
 }
 window.dpGantt={open(){if(!allowed())return;if(!$('gt-status'))mount();run(load);}};
 window.addEventListener('tracker-tasks-synced',e=>{
  if(!state||!allowed()||!Array.isArray(e.detail))return;
  state.tasks=e.detail.map(t=>({id:String(t.id),name:t.name,mainPIC:t.mainPIC||'',assigned:t.assigned||[],deadline:t.deadline||'',status:t.status,chapter:t.chapter||''}));
  if($('gt-chart'))draw();
 });
 function install(){if(!auth)return;auth.onAuthStateChanged(()=>{session++;state=null;if($('gantt')){$('gantt').innerHTML='';$('gantt').classList.add('hidden');}if($('navGantt'))$('navGantt').style.display=allowed()?'':'none';});}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
