const vm=require('vm'),fs=require('fs'),assert=require('assert/strict');
const elements=new Map(),listeners={};
function el(id=''){const e={id,hidden:true,innerHTML:'',textContent:'',style:{},dataset:{},tagName:'DIV',isConnected:true,inert:false,disabled:false,attributes:{},classList:{contains:()=>true},setAttribute(k,v){this.attributes[k]=v},addEventListener(k,f){this[k]=f},appendChild(){},prepend(x){elements.set(x.id,x)},focus(){document.activeElement=this},querySelector(s){if(!elements.has(s))elements.set(s,el(s));return elements.get(s)},querySelectorAll(){return sections}};return e;}
const sections=[0,1,2,3].map(i=>{const x=el();x.dataset.pmSection=String(i);return x});
const body=el();body.children=[];body.appendChild=e=>{body.children.push(e);elements.set(e.id,e)};
const document={readyState:'complete',body,activeElement:el('presentationBtn'),getElementById:id=>id==='loginScreen'?null:elements.get(id),querySelector:()=>el(),createElement:()=>el(),addEventListener:(k,f)=>listeners[k]=f};
const ctx={document,window:{addEventListener:(k,f)=>listeners[k]=f},Intl,Date,console,MutationObserver:class{observe(){}},tasks:[{id:1,name:'Blocked test',chapter:'Chapter 1',status:'Blocked',deadline:'2000-01-01',mainPIC:'Shamiel'},{id:2,name:'Done test',status:'Done'},{id:3,name:'<img onerror=alert(1)>',status:'In Progress',deadline:'2099-01-01'},{id:4,name:'Invalid date',deadline:'2026-02-30'}],meetings:[{title:'Review',date:'2020-01-01',mom:{summary:'Actual notes',actionItems:[{text:'Linked done',taskId:2},{text:'Unlinked action'},{text:'Deleted linked',taskId:88},{text:'Finished',done:true}]}}],CHAPTERS:['Chapter 1','Chapter 2'],chapterReviews:{'Chapter 1':{status:'revision'}},SV_REVIEW_FLOW:[{key:'revision',label:'Revision'}]};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname, 'presentation.js'),'utf8'),ctx);listeners['tracker-tasks-synced']();elements.get('presentationBtn').click();
const html=()=>elements.get('#pm-content').innerHTML;
assert.match(html(),/<strong>1<\/strong><span>Tasks done/);assert.match(html(),/<strong>3<\/strong><span>Tasks open/);assert.match(html(),/<strong>1<\/strong><span>Tasks overdue/);
sections[1].onclick();assert.match(html(),/SV review: Not recorded/);assert.match(html(),/SV review: Revision/);
sections[2].onclick();assert.match(html(),/confirm during discussion/);listeners.keydown({key:'ArrowRight',preventDefault(){}});assert.match(html(),/Actual notes/);
sections[3].onclick();assert(!html().includes('Linked done'));assert(!html().includes('Finished'));assert(html().includes('Deleted linked'));assert(html().includes('&lt;img'));assert(!html().includes('<img'));assert(html().includes('No date set'));
ctx.tasks.push({id:10,name:'New task',status:'Done'});assert(!html().includes('New task'));elements.get('#pm-refresh').onclick();sections[0].onclick();assert.match(html(),/<strong>2<\/strong><span>Tasks done/);
elements.get('#pm-close').onclick();assert(elements.get('presentationMode').hidden);
ctx.tasks=[];ctx.meetings=[];ctx.chapterReviews={};elements.get('presentationBtn').click();assert.match(html(),/<strong>0<\/strong><span>Tasks done/);sections[3].onclick();assert.match(html(),/No open tasks/);
console.log('PASS: snapshot counts, overdue/invalid dates, chapter review fallback, blockers, minutes, linked-action deduplication, HTML escaping, refresh, keyboard navigation, close and empty states.');
