const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const {validatePlan}=require('./gantt-validation');
const tasks=[{id:1,name:'Sizing',status:'In Progress',deadline:'2026-10-20'}];
const plan={milestones:[{id:'m1',name:'Report',date:'2026-10-25',target:'2026-10-23',source:'Outline'}],schedules:[{taskId:'1',milestoneId:'m1',start:'2026-10-01',target:'2026-10-19'}]};
test('valid plan preserves separate official, internal and task dates',()=>{const p=validatePlan(plan,tasks);assert.equal(p.milestones[0].date,'2026-10-25');assert.equal(tasks[0].deadline,'2026-10-20');assert.equal(p.schedules[0].target,'2026-10-19');});
test('rejects impossible dates, reverse intervals, missing tasks and duplicate IDs',()=>{for(const mutate of [p=>p.milestones[0].date='2026-02-30',p=>p.milestones[0].target='2026-10-26',p=>p.schedules[0].start='2026-10-21',p=>p.schedules[0].taskId='2',p=>p.schedules[0].milestoneId='bad',p=>p.milestones.push(p.milestones[0]),p=>p.schedules.push(p.schedules[0])]){const p=structuredClone(plan);mutate(p);assert.throws(()=>validatePlan(p,tasks));}});
function service(){let saved={...structuredClone(plan),revision:2};const writes=[];const db={doc:path=>({path,get:async()=>({data:()=>path==='trackerData/tasks'?{list:tasks}:saved})}),runTransaction:async fn=>fn({get:async ref=>ref.get(),set:(ref,data)=>{writes.push(ref.path);saved=data;}})};const ctx={exports:{},require:n=>n==='firebase-functions/v2/https'?{onCall:(_,f)=>f,HttpsError:class extends Error{constructor(c,m){super(m);this.code=c;}}}:n==='firebase-functions/params'?{defineSecret:()=>({})}:n==='firebase-admin/app'?{getApps:()=>[{}]}:n==='firebase-admin/firestore'?{getFirestore:()=>db}:require(n)};vm.runInNewContext(fs.readFileSync(__dirname+'/index.js','utf8'),ctx);return {call:ctx.exports.ganttPlanner,writes};}
const leader={uid:'leader',token:{email:'2023305361@student.uitm.edu.my'}};
test('anonymous, member and lecturer cannot read or write private plans',async()=>{const {call,writes}=service();for(const auth of [undefined,{uid:'member',token:{email:'2023126973@student.uitm.edu.my'}},{uid:'lecturer',token:{email:'lecturer@example.com'}}])for(const action of ['read','save'])await assert.rejects(call({auth,data:{action,plan,revision:2}}),e=>e.code==='permission-denied');assert.equal(writes.length,0);});
test('save writes only private plan, rejects stale revision and reads all task statuses',async()=>{const {call,writes}=service();await call({auth:leader,data:{action:'save',plan,revision:2}});assert.deepEqual(writes,['workloadPrivate/gantt-plan']);await assert.rejects(call({auth:leader,data:{action:'save',plan,revision:2}}),e=>e.code==='failed-precondition');const read=await call({auth:leader,data:{action:'read'}});assert.equal(read.plan.revision,3);assert.equal(read.tasks.length,1);});
